# We want all PRs built but only merges on master branch and tags under semantic version scheme
branches:
  only:
  - master
  - /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/

jobs:
  include:
    - stage: Build and Test on OpenJDK11
      name: Build and Test on OpenJDK11
      language: java
      jdk:
        - openjdk11
      install:
        - mvn install -q -Dmaven.test.skip -Dmaven.javadoc.skip -B -V
      script:
        - >
          mvn verify \
            -Dbucketeer.s3.access_key="${AWS_ACCESS_KEY_ID}" \
            -Dbucketeer.s3.secret_key="${AWS_SECRET_ACCESS_KEY}" \
            -Dcdn.distribution.id="${CLOUDFRONT_DISTRO_ID}" \
            -Dbucketeer.iiif.url="${BUCKETEER_IIIF_URL}" \
            -Dbucketeer.slack.test_user_handle="${SLACK_TEST_USER_HANDLE}" \
            -Dbucketeer.slack.oauth_token="${SLACK_OAUTH_TOKEN}" \
            -Dbucketeer.slack.channel_id="${SLACK_CHANNEL_ID}" \
            -Dbucketeer.slack.error_channel_id="${SLACK_ERROR_CHANNEL_ID}"

    - stage: Trigger Jenkins for Containerization
      name: Trigger Jenkins for Containerization
      language: minimal
      deploy:
        - provider: script
          script: .travis/trigger-docker-build.sh
          on:
            branch: master
      if: (NOT type IN (pull_request)) AND (branch = master)
    - stage: Trigger Jenkins with Tag for Containerization
      name: Trigger Jenkins with Tag for Containerization
      language: minimal
      deploy:
        - provider: script
          script: .travis/trigger-docker-build.sh
          on:
            tags: true
      if: (NOT type IN (pull_request)) AND (branch =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/)

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change
