language: java

script:
- mvn package

# We want all PRs built but only merges on master branch
#  However, when we first create a new project, we need to comment this out
branches:
  only:
  - master

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change
