language: java

jdk:
- oraclejdk11
- openjdk11

install:
  - mvn install -q -Dmaven.test.skip -Dmaven.javadoc.skip -B -V

script:
- mvn verify -Dbucketeer.s3.access_key="$AWS_ACCESS_KEY_ID" -Dbucketeer.s3.secret_key="$AWS_SECRET_ACCESS_KEY"

# We want all PRs built but only merges on master branch
#  However, when we first create a new project, we need to comment this out
branches:
  only:
  - master

after_success:
- |
  # The following vars are stored encrypted in TravisCI
  # JENKINS_USER
  # JENKINS_USER_PASS
  # JENKINS_URL

  # Trigger latest dockerhub build if commit on master branch
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    curl -I -u "${JENKINS_USER}:${JENKINS_USER_PASS}" "${JENKINS_URL}"
  # Else if there's a tag, trigger a tag build
  elif [[ $TRAVIS_TAG != "" && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    curl -I -u "${JENKINS_USER}:${JENKINS_USER_PASS}" "${JENKINS_URL}&BUCKETEER_VERSION=${TRAVIS_TAG}"
  # Else we're assuming this is using another branch other than master
  elif [[ $TRAVIS_BRANCH != "master" && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG == "" ]]; then
    curl -I -u "${JENKINS_USER}:${JENKINS_USER_PASS}" "${JENKINS_URL}&BUCKETEER_VERSION=${TRAVIS_BRANCH}"
  fi

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change
