language: java

jdk:
- oraclejdk11
- openjdk11

env:
  global:
    secure: "O9sCrqbFlD2/k9/xocMDeVqCUb1EKTITHD/9OPDB+ttw6dZkIqhz43wXGVteg3Gd+POd/cKOc/5A6yxibyUmYIR9OjkJP9rAKsBw8tFH/ivqUUUrSDOc5j9rgdvnEtV50G3Wo2bEASd0JUHvSdc8HX+Vz4PAc7cDSUvBiGdJ/b5kxMdH4bz74khZANxrHd/afGzNaIMmHITBUsm3SXagcQ8mCySgVEoPRaXHtnlLvUhQstYLrXARlnO25gAunWFoLdMEmZmIx8caNm+EG8Pca/yH8IK6lku87WDGPjqkG0CETHn+Laa6n8DOgif30sRoLRN4Z/2pSg4qmcqznrAezLPMap08eQiSCAOLUgV4D5/MYgL1EEJTOQoOKFFMkYdcnAgjdMrXZqlsv6LWoKCbYGKi9csCEElf9cgBb4R2mL4drYll804oVzrnYYHq2RAbWPo1zCkalX/ZdGog49CxZrcC4UWxNugF9f3BDADeC9f1PK/aMoFM6EWXefF3RNNN0TwAw1kxcWQ+/tFEh+XYTPnLPMrciW3MvB/ABDuQvpL7V4QQrE0z3PABi3yhGQ8c2gLrVsGR26wkhlmu1388zUunU9WxaH5CmH9eILzdf+bkOCNHm9JbPKlNku/wMX1bwgmdaprkcjMCImN1CsH3IyTXR9QeD68jHmb71s+XKFY="
    secure: "kzZQ7AMsUkJ0kvryiabYK3HlIp9x6dWowpU2/rax8oF5b4C/SN6YhFGQayR22d4l5OWAhJQckB69ny6ucK4jyf88nRP7QmLL7xHYq4uZq7KVqwetCA3bq+68RGN6iFUc/fF0xrjPuXkDmfBJoolIzLQiQbrJLoK+dV8Lz1A6Z3MoU0QTHz+PBpZ7cUdcDGzpV8gx0+rwIdTd3mxkBx8g6O0hPeEA7m7A4jo6hho8V7cVp41ItIDPkeod0Qw+Rz3RYDXrt2eAT3AqKgVEbB7FD/jjAz7/BC0HAjZ+D4M1JG9Ab1MRexPaaDeop+VxotS8bSmT+PVeUNsVqrIwVlv7pi0ZRwGqLqHYaNl6i8W91Bmft6rwZq7flpO0YNH2XLHlEB0zhUGg5LbpD4iNpNXVn4vxm7jJ+DId7mAgiSVIGa/FW9e12MEUZP3Ev4tnTXJ7rY90hDzW1A+ddzkAkVr2uBb4EjGJZ+idsGA5Wlz9ChAve1gbA4/RB5WJDq+Z1o591qkl1LI4i3AEnYr6W5bEfLYnkMBV94al9LRRKdmYNW+FJ3rft/CXwfE8n6JkgijRyty0oI6jv4jYiiqMbOUUgdd1mCRNm5vnCLKaJHRuETxZG+gcFf/WUmGf06nVUwqKlVrosbdK08MGthhPlX51LOA6B8a1oGgsFaZ+WszL+94="
    secure: "bgLoQYK4IrYyY7GOSkjKEVCKwBMcc0mvB+cWd+iyPF9+QoCjs+AUwGOc4f4hGtuDQCsY+Q/w7QyrRZgNQBRCJLB+21p3+d4EZMHyYH0r22sE7erQOwdcqLAFuiyaMVx1IORFk/Poj4QRBcj/1RpCdFP1/ks1FALO5080NvIavY9xNUCNJMq3fxPJa5D1KO2WO/j3i92e99RM//2JYelz5nqC8JzIjcFLgxIRKX6m8Rfl6eWBcniRfiQNfiAEXjDDcTI9k4Mvd5SR3rqGiDJz0NH9+6+VAjLl2FGM6zOG1wknWFOh2UWTlP8CSRJh8wzGtvQ0WBOemKJcJ2OACFzWq8Kl+DcxDi2RFGwFBwwDSHi6V9qyrORi/2DIw2CuEpyNV3b58/W2IrAxO5xXESnAiHmz6Lq/9QdoGL+yQwb5HKG67NeytzC3wUGD355/ggZl/CB0NvBwDAUtatLbKQxeNsqSmfPnQDmhsdb0SFSs4py1Ho9KPogShrGRcyDKgPvlpFnDCJzDuACkpUBUKOcvJjVdkkHo3ufgRNSjArYeAkx4VLTnwIlhzD0RqAhk69zezF0u7rC5fWgUM+Dpfo8fK5/lH4cNHhIeHvxoHiMsC8OzQjT0HrRv1WS+SeMc2220qHzp3ZDxG83KgbFkyL0Pnl7LAOL/38D/pTpqHpuExIw="


install:
  - mvn install -q -Dmaven.test.skip -Dmaven.javadoc.skip -B -V

script:
- mvn verify -Dbucketeer.s3.access_key="$AWS_ACCESS_KEY_ID" -Dbucketeer.s3.secret_key="$AWS_SECRET_ACCESS_KEY"

# We want all PRs built but only merges on master branch
#  However, when we first create a new project, we need to comment this out
branches:
  only:
  - master

after_success:
- |
  # The following vars are stored encrypted in TravisCI
  # JENKINS_USER
  # JENKINS_USER_PASS
  # JENKINS_URL

  # Trigger latest dockerhub build if commit on master branch
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    curl -I -u "${JENKINS_USER}:${JENKINS_USER_PASS}" "${JENKINS_URL}"
  # Else if there's a tag, trigger a tag build
  elif [[ $TRAVIS_TAG != "" && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    curl -I -u "${JENKINS_USER}:${JENKINS_USER_PASS}" "${JENKINS_URL}&BUCKETEER_VERSION=${TRAVIS_TAG}"
  # Else we're assuming this is using another branch other than master
  elif [[ $TRAVIS_BRANCH != "master" && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG == "" ]]; then
    curl -I -u "${JENKINS_USER}:${JENKINS_USER_PASS}" "${JENKINS_URL}&BUCKETEER_VERSION=${TRAVIS_BRANCH}"
  fi

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change
