openapi: "3.0.0"
info:
  version: 1.0.0
  title: Bucketeer API
  description: A TIFF to JP2 to S3 Bucket Microservice
  license:
    name: The 3-Clause BSD License
    url: https://opensource.org/licenses/BSD-3-Clause
  contact:
    name: UCLA Library Services Team
    email: lib_softwaredev-services@library.ucla.edu
servers:
  - url: http://bucketeer.library.ucla.edu/
paths:
  /status:
    get:
      summary: Application Status
      description: Requests an application status check
      operationId: getStatus
      responses:
        '200':
          description: OK
  /batch/jobs:
    get:
      summary: Jobs in Progress
      description: A listing of batch jobs currently in practice
      operationId: getJobs
      responses:
        '200':
          description: OK
          content:
            application/json: {}
        '500':
          description: There was an internal server error
  /batch/jobs/{job-name}:
    get:
      summary: Statuses of a Job
      description: A listing of images being processed in a job
      operationId: getJobStatuses
      responses:
        '200':
          description: OK
          content:
            application/json: {}
        '404':
          description: The job was not found
        '500':
          description: There was an internal server error
    delete:
      summary: Batch Job Deletion
      description: Deletes the job with the supplied name
      operationId: deleteJob
      responses:
        '204':
          description: No content, the job has been deleted
        '403':
          description: Forbidden
        '500':
          description: Internal server error
    parameters:
       - in: path
         name: job-name
         required: true
         schema:
           type: string
         description: The batch job name
  /batch/jobs/{job-name}/{image-id}/{success}:
    patch:
      summary: Batch Job Status
      description: Updates a batch job that's in process
      operationId: updateBatchJob
      responses:
        '204':
          description: The job status was successfully updated
        '404':
          description: The job status was not found
        '500':
          description: There was an internal server error
    parameters:
       - in: path
         name: job-name
         required: true
         schema:
           type: string
         description: The batch job name
       - in: path
         name: image-id
         required: true
         schema:
          type: string
         description: The processed image ID
       - in: path
         name: success
         required: true
         schema:
          type: boolean
         description: Whether the image was successfully processed
  /batch/input/csv:
    post:
      summary: CSV Batch Conversion
      description: Loads a bunch of images into Bucketeer's batch ingest workflow so that Cantaloupe can access them
      operationId: loadImagesFromCSV
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                slack-handle:
                  type: string
                csvFileToUpload:
                  type: string
                  format: binary
                failure:
                  type: string
      responses:
        '200': 
          description: An HTML page informing the user that their job has been queued
          content:
            text/html:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request (missing Slack handle/CSV file or invalid CSV uploaded)
        '415':
          description: Unsupported media type (i.e. not a CSV file)
  /{image-id}/{file-path}:
    get:
      summary: New JPEG 2000 Image
      description: Requests a new image be loaded into Bucketeer's ingest workflow so that Cantaloupe can access it
      operationId: loadImage
      responses:
        '200':
          description: loadImage Confirmation message
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the load succeeded
                  message:
                    type: string
                    description: Any related text about the loadImage operation
    parameters:
       - in: path
         name: image-id
         required: true
         schema:
           type: string
         description: The image ID
       - in: path
         name: file-path
         required: true
         schema:
          type: string
         description: The local image path
