openapi: "3.0.0"
info:
  version: 1.0.0
  title: Bucketeer API
  description: A TIFF to JP2 to S3 Bucket Microservice
  license:
    name: The 3-Clause BSD License
    url: https://opensource.org/licenses/BSD-3-Clause
  contact:
    name: Kevin S. Clarke
    email: ksclarke@library.ucla.edu
    url: https://www.library.ucla.edu/staff/kevin-sean-clarke
servers:
  - url: http://bucketeer.library.edu/
paths:
  /ping:
    get:
      summary: ping, is this thing on?
      operationId: getPing
      responses:
        '200':
          description: OK
  /{imageId}/{filePath}:
    get:
      summary: loadImage, local TIFF -> JP2 in S3
      description: Reads a TIFF file from the file system, turns it into a lossy JP2 image, and uploads that image into the configured S3 bucket.
      operationId: loadImage
      responses:
        '200':
          description: loadImage Confirmation message
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the load succeeded
                  message:
                    type: string
                    description: any related text about the loadImage operation
    parameters:
       - in: path
         name: imageId
         required: true
         schema:
           type: string
         description: The image ID
       - in: path
         name: filePath
         required: true
         schema:
          type: string
         description: The local image path

