#! /bin/bash

#
# A simple script to return the next version of a Maven snapshot project.
#

VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='0.0.1-SNAPSHOT' --non-recursive exec:exec)

echo ${VERSION%"-SNAPSHOT"}
